import './scss/page/page.scss';
import './scss/gradient/gradient.scss';
import './scss/control/control.scss';
import './scss/button/button.scss';
import './scss/search/search.scss';
import './scss/main/main.scss';
import './scss/date-time/date-time.scss';
import './scss/quote/quote.scss';
import './scss/greeting/greeting.scss';
import './scss/focus/focus.scss';
import './scss/weather/weather.scss';
import './scss/errors/errors.scss';

import './scss/date-time';
import './scss/page';
import './scss/main';
import './scss/greeting';
import './scss/quote';
import './scss/search';
